language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
branches:
  only:
  - master
before_install:
  - chmod a+x gradlew
script:
  - ./gradlew build
notifications:
  email:
    - lzy7750015@qq.com